version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: digitalcraft_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalcraft
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  apache:
    image: httpd:2.4
    container_name: digitalcraft_apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/html:/usr/local/apache2/htdocs/
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: digitalcraft_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: