version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: digitalcraft_mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalcraft
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - digitalcraft_prod_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitalcraft_backend_prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=digitalcraft
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - digitalcraft_prod_network

  nginx:
    image: nginx:alpine
    container_name: digitalcraft_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - digitalcraft_prod_network

volumes:
  mysql_data_prod:

networks:
  digitalcraft_prod_network:
    driver: bridge 